### ISSUE TITLE
Document not Found

### ISSUE THREAD

**Issue by OssamaLouati** [KOBeerose/RTC#2]
https://rtc.ma/pdfs/TSI/spe-crs/gm/Equilibrage%20dynamique.pdf
-this link is not available 
+TSI/ mechanical engineering for dynamic balancing

**Comment by KOBeerose** [comment]
Thanks for the feedback 😃, it was a typo in the file name.
It should work now! https://rtc.ma/pdfs/TSI/spe-crs/gm/Equilibrage%20dynamique%20.pdf
